apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
apiServerCertSANs:
- "kubernetes.selit.ru"
api:
    controlPlaneEndpoint: "kubernetes.selit.ru:443"
etcd:
  local:
    extraArgs:
      listen-client-urls: "https://127.0.0.1:2379,https://10.0.0.6:2379"
      advertise-client-urls: "https://10.0.0.6:2379"
      listen-peer-urls: "https://10.0.0.6:2380"
      initial-advertise-peer-urls: "https://10.0.0.6:2380"
      initial-cluster: "fnc-master-1=https://10.0.0.5:2380,fnc-master-2=https://10.0.0.6:2380"
      initial-cluster-state: existing
    serverCertSANs:
      - fnc-master-2
      - 10.0.0.6
    peerCertSANs:
      - fnc-master-2
      - 10.0.0.6
