kind: PersistentVolume
apiVersion: v1
metadata:
  name: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.4
    path: "/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-sonarqube-extensions
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 3Gi
#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: claim-sonarqube-data
#spec:
#  accessModes:
#    - ReadWriteMany
#  storageClassName: ""
#  resources:
#    requests:
#      storage: 3Gi

