kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-sonarqube-extensions
  annotations:
    volume.beta.kubernetes.io/storage-class: "selit-nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-sonarqube-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "selit-nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

