apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    deployment: memcached
  name: memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - image: memcached
        name: memcached
        ports:
          - containerPort: 11211
            name: memcached
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Service
apiVersion: v1
metadata:
  labels:
    service: memcached
  name: memcached
spec:
  selector:
    app: memcached
  ports:
    - protocol: TCP
      port: 11211
      name: memcached 
